@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDcwNjAxMDN9.TWEMdWn6-e1tl4DBM1AQkNESM5zLMVo2i3fQ1WEkTKA

@domain = http://localhost:3000


###Index equipment sets
GET {{ domain }}/equipment-sets
Authorization: Bearer {{ jwt }}

###Create equipment set
POST {{ domain }}/equipment-sets
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "name": "Revenant fdasfd Set",
  "oldschooljs_monster_id": 12915,
  "items": [
    {
      "oldschooljs_item_id": 4151,
      "slot": "2h"
    },
     {
      "oldschooljs_item_id": 2,
      "slot": "head"
    },
     {
      "oldschooljs_item_id": 3,
      "slot": "body"
    },
     {
      "oldschooljs_item_id": 4,
      "slot": "legs"
    },
     {
      "oldschooljs_item_id": 4,
      "slot": "feet"
    },
     {
      "oldschooljs_item_id": 4,
      "slot": "hands"
    },
     {
      "oldschooljs_item_id": 4,
      "slot": "cape"
    },
     {
      "oldschooljs_item_id": 4,
      "slot": "ammo"
    },
     {
      "oldschooljs_item_id": 4,
      "slot": "neck"
    },
    {
      "oldschooljs_item_id": 5,
      "slot": "ring"
    }
  ]
}

###Show equipment set
GET {{ domain }}/equipment-sets/4
Authorization: Bearer {{ jwt }}

###Update equipment set
PATCH {{ domain }}/equipment-sets/4
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "name": "Magic poopoo Set",
  "oldschooljs_monster_id": 777,
  "items": [
     {
      "oldschooljs_item_id": 2,
      "slot": "helm"
    },
     {
      "oldschooljs_item_id": 3,
      "slot": "chest"
    },
     {
      "oldschooljs_item_id": 4,
      "slot": "legs"
    },
    {
      "oldschooljs_item_id": 5,
      "slot": "ring"
    }
  ]
}

###Delete equipment set
DELETE {{ domain }}/equipment-sets/52
Authorization: Bearer {{ jwt }}