@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDYzNDk0NjB9.Xjxj_rzvK6irjic8Jn3pDnOqSY_9UYsMQ5yQ0nyOSIM

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "display_name": "kevin",
  "email": "kevin@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "kevin@test.com",
  "password": "password"
}

###Show User
GET http://localhost:3000/users/3
Authorization: Bearer {{ jwt }}

###Update User
PATCH http://localhost:3000/users/3
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "email": "kevin-test@test.com",
  "password_confirmation": "password222"
}

###Delete User
DELETE http://localhost:3000/users/3
Authorization: Bearer {{ jwt }}
