@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDcwNjAxMDN9.TWEMdWn6-e1tl4DBM1AQkNESM5zLMVo2i3fQ1WEkTKA

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "display_name": "brian",
  "email": "brian@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "kevin@test.com",
  "password": "password"
}

###Show User
GET http://localhost:3000/users/2
Authorization: Bearer {{ jwt }}

###Update User
PATCH http://localhost:3000/users/2
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "display_name": "brian",
  "password": "password",
  "password_confirmation": "password"
}

###Delete User
DELETE http://localhost:3000/users/2
Authorization: Bearer {{ jwt }}
